on:
    issues:
        types: [labeled]

jobs:
    release_prod:
        if: github.event.label.name == 'to-deploy'
        name: realease prod
        runs-on: ubuntu-20.04
        steps:
            - run: echo "Releasing in production"
            - run: echo "Close issue"