on:
    release:
        types: [published]

jobs:
    build_artifact:
        name: build artifact
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Build artifact
              run: zip -r artifact.zip . -x \*.git\* \*\*/node_modules/\*

            - name: Upload release to release
              id: upload_release
              uses: actions/upload-release-asset@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                upload_url: ${{ github.event.release.upload_url }}
                asset_path: ./artifact.zip
                asset_name: artifact.zip
                asset_content_type: application/zip

            - name: Realease in preprod
              run: echo "Releasing in preprod"

            - name: Create MEP issue
              uses: JasonEtco/create-an-issue@v2
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                ARTIFACT: ${{ steps.upload_release.outputs.browser_download_url }}
              with:
                filename: .github/release-ticket.md
