on:
    label:
        types: [created, edited]

jobs:
    release_prod:
        name: realease prod
        runs-on: ubuntu-20.04
        steps:
            - run: echo "Releasing in production"
            - run: echo "Close issue"
        if: github.event.label.name == 'to-deploy'