on:
    release:
        types: [published]

jobs:
    release_job:
        name: realease preprod
        runs-on: ubuntu-20.04
        steps:
            - run: echo "Releasing in preprod"
    generate_ticket:
        name: generate MEP ticket
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - uses: JasonEtco/create-an-issue@v2
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                ADJECTIVE: great
              with:
                filename: .github/release-ticket.md